version: 2
jobs:
  build:
    docker:
      - image: "node:14.20.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm ci
      - run: npm run test
      - run: npm run build-storybook
      - run: npm run build

      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'

    working_directory: ~/repo
