name: PR Checks

on:
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: "19.x"
      - name: cache node modules
        uses: actions/cache@v2
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Build
        working-directory: ./app
        run: npm run build

      - name: Test
        working-directory: ./app
        run: npm run test

      - name: Lint
        working-directory: ./app
        run: npm run lint